// Copyright © 2023-2024 Wei Shen <shenwei356@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// This package is modified from https://github.com/vejnar/nwalgo
package align

import (
	"fmt"
	"testing"
)

func TestNW(t *testing.T) {
	tests := [][]string{
		{"GATTACA", "GCATGCG"},
		{"ATGTTAT", "ATCGTAC"},

		// {
		// 	"ACGCGTAGATCTTCAGTGCCGCGGACACCTGCCGCTCCCGGGCCCTCGGACGCCAACCCGCAGCGTCCCGAGCCGCCCGGCGGGCGACCAACTCCTCGTCGCTGACCAGCAGGTTCACGCTGCGGTCGGGGATGGAGAACTCGATGGAGTCCCCGTCCTCGACCAGCCCGATCGCGCCGCCCGCGGCGGCCTCCGGCANGACGTGGCCCACGCTCAACCCGGACGAGCCGCCCGAGAACCGACCGTCGGTGATCAACGNCGCGGGGCCCAGCCCGACGCCCTTGAGGTAGGAGGTCGGGTACAGCATTTCCTGCATGCCCGGGCCGCCCTTGGGGCCCTCGTACCGGACGACCACGACATCGCCTGCCACGATCCTGCCGCCGAGGATCATCTCGACGGCCTCCTCCTGCGACTCGGCGACCTTCGCGGTGCCGGTGAAGCGCCACTGGTGCTCGGGCACGCCCGCGGTCTTCACGATGGCGCCGTCGGGCGCCAGATTCCCCTTGAGGACGGCCAGGCCGCCGTCGGCGGTGTAGGCGTGCGCGACGTCCCGGATGCAGCCGTTGGCGGCATCGGTGTCCAGCGAATCCCAGCGGTTGTCGGACGAGAACGGCTCGGTCGTCCGGATGCCGCCGGGCGCGGCGTGCCACAGCTCGGACGACTTCTCGGTGGCGCTGCCCGACCGGATGTCCCAGGCGTCCAGCCAGTCGGCGAGGAGTCGGCGTGCACGGCATGGACGTTCTCCTCNCAGCAGCCCGCCCCGGCGCAGTTCGCCCAGGATCGCGGGCATGCCGCCGGCGCGATGCACGTCCTCCATGTAGTACGACGTGGTGTTCGGGGCGACCTTGCACAGGCACGGGGTGACCCGCGACAGCGCATCGATGTCGTCCAGGGTGAAGTCGACGCCGGCCTCGACCGCCGCGGCGAGGATGTGCAGCACCGTGTTGGTCGACCCGCCCATCGCGATGTCGAGCCGCATCGCGTTGGCGAAAGCCTCNNCGGTGGCGATCGAACGGGGCAGGACGGACGCGTCGTCGTCCTCGTAGTAGCGCTTCGCGAGCTGGACGACCAGCCGGCGGCGGCCAGGAACAGTTCCTTGCGGGCGGCGGCGGTGGCCAGGGTNGGAACCGTTGCCCGGCAGCCCGAGGCCCAGCGCTTCGACCAGGCAGTTCATCGAGTTGGCCGTGAACATGCCCGAGCAGGAGCCGCAGGTCGGGCAGGCCGACTGCTCGACGGTCAGCAGTTGCTCGTCGGTGACCGAATCGTCCACGGCCTTGGACATGGCGTCGATGAGGTCGAGGCGGGTCGCGACCCGTCGTCCGATGACGGCCTTGCCGGCCTCCATCGGACCGCCCGAGACGAACACCGTCGGGATGTTCAGCCGCAGCGCCGCCAGCAGCATGCCGGGGGTGATCTTGTCGCAGTTGGAGATGCAGACCAGGGCGTCCGCGCAGTGCGCGTTGACCATGAACTCGACCGAGTCGGCGATCAGCTCGCGGCTGGGCAGCGAGTAGAGCATGCCGCCGTGGCCCATCGCGATCCCGTCGTCGACGGCGATGGTGTTGAACTCCCGGCCGACCCCGCCGGCGTCGCGCACCGCGCCGGCGACCAGCGCCCCCATGTCGCGCAGGTGCACGTGACCGGGTACGAACTGGGTGAAGCTGTTGGCGATCGCCACGATCGGCTTGCCGAAGTCGGACTCGCCCATGCCGGTGGCGCGCCACAGGGCGCGGGCGCCGGCCATGTTGCGACCGTGCGTGGTGGTCCGGGAACGCAGTGCAGGCATGGGGGCAAGGCTACGCGGTCGGCGCCGGACGGCGGCGCTGTCCCGGCGGCGAGCGGCGTTCCGCCGGGTCGGGGCGGGCGGTTCGGCGTGGCCGACCGGTCGGGACGTGTGCCCGTTCGGGGCCTCATAGGAGCAGCTCGTACGTTCGCAGGGTCATGCCGGGACGCGGCGACCAGTCGGCGGCTGGGGTGCGGGTGAACCCGAGGCGCTCGTA",
		// 	"CGTAGATCTTCAGTGCCGCGGACACCTGCCGCTCCCGGGCCCTCGGACGCCAACCCGCAGCGTCCCGAGCCGCCCGGCGGGCGACCAACTCCTCGTCGCTGACCAGCAGGTTCACGCTGCGGTCGGGGATGGAGAACTCGATGGAGTCCCCGTCCTCGACCAGCCCGATCGCGCCGCCCGCGGCGGCCTCCGGCGAGACGTGGCCCACGCTCAACCCGGACGAGCCGCCCGAGAACCGACCGTCGGTGATCAACGCGCACTTGGGGCCCAGCCCGACGCCCTTGAGGTAGGAGGTCGGGTACAGCATTTCCTGCATGCCCGGGCCGCCCTTGGGGCCCTCGTACCGGACGACCACGACATCGCCTGCCACGATCCTGCCGCCGAGGATCATCTCGACGGCCTCCTCCTGCGACTCGGCGACCTTCGCGGTGCCGGTGAAGCGCCACTGGTGCTCGGGCACGCCCGCGGTCTTCACGATGGCGCCGTCGGGCGCCAGATTCCNCTTGAGGACGGCCAGGCCGCCGTCGGCGGTGTAGGCGTGCGCGACGTCCCGGATGCAGCCGTTGGCGGCATCGGTGTCCAGCGAATCCCAGCGGTTGTCGGACGAGAACGGCTCGGTCGTCCGGATGCCGCCGGGCGCGGCGTGCCACAGCTCGGACGACTTCTCGGTGGCGCTGCCCGACCGGATGTCCCAGGCGTCCAGCCAGTCGGCGAGGGAGTCGGCGTGCACGGCATGGACGTTCTCCTCCAGCAGCCCGCCCCGGCGCAGTTCGCCCAGGATCGCGGGCATGCCGCCGGCGCGATGCACGTCCTCCATGTAGTACGACGTGGTGTTCGGGGCGACCTTGCACAGGCACGGGGTGACCCGCGACAGCGCATCGATGTCGTCCAGGGTGAAGTCGACGCCGGCCTCGACCGCCGCGGCGAGGATGTGCAGCACCGTGTTGGTCGACCCGCCCATCGCGATGTCGAGCCGCATCGCGTTGGCGAAAGCCTCCTTGGTGGCGATCGAACGGGGCAGGACGGACGCGTCGTCGTCCTCGTAGTAGCGCTTCGCGAGCTGGACGACCAGCCGGCCGGCGGCCAGGAACAGTTCCTTGCGGGCGGCGGCGGTGGCCAGGGTGGAACCGTTGCCCGGCAGCCCGAGGCCCAGCGCTTCGACCAGGCAGTTCATCGAGTTGGCCGTGAACATGCCCGAGCAGGAGCCGCAGGTCGGGCAGGCCGACTGCTCGACGGTCAGCAGTTGCTCGTCGGTGACCGAATCGTCCACGGCCTTGGACATGGCGTCGATGAGGTCGAGGCGGGTCGCGACCCCGTCCTTGATGACGGCCTTGCCGGCCTCCATCGGACCGCCCGAGACGAACACCGTCGGGATGTTCAGCCGCAGCGCCGCCAGCAGCATGCCGGGGGTGATCTTGTCGCAGTTGGAGATGCAGACCAGGGCGTCCGCGCAGTGCGCGTTGACCATGAACTCGACCGAGTCGGCGATCAGCTCGCGGCTGGGCAGCGAGTAGAGCATGCCGCCGTGGCCCATCGCGATCCCGTCGTCGACGGCGATGGTGTTGAACTCCCGGCCGACCCCGCCGGCGTCGCGCACCGCGCCGGCGACCAGCGCCCCCATGTCGCGCAGGTGCACGTGACCGGGTACGAACTGGGTGAAGCTGTTGGCGATCGCCACGATCGGCTTGCCGAAGTCGGACTCGCCCATGCCGGTGGCGCGCCACAGGGCGCGGGCGCCGGCCATGTTGCGACCGTGCGTGGTGGTCCGGGAACGCAGTGCAGGCATGGGGGCAAGGCTACGCGGTCGGCGCCGGACGGCGGCGCTGTCCCGGCGGCGAGCGGCGTTCCGCCGGGTCGGGGGCGGGCGGTTCGGCGTGGCCGACCGGTCGGGACGTGTGCCCGTTCGGGGCCTCATAGGAGCAGCTCGTACGTTCGCAGGGTCATGCCGGGACGCGGCGACCAGTCGGCGGCTGGGGTGCGGGTGAACCCGAGGCGCTCGTA",
		// },
	}

	var a, b []byte
	alg := NewAligner(&AlignOptions{
		MatchScore:     1,
		MisMatchScore:  -1,
		GapScore:       -1,
		SaveAlignments: true,
		SaveMatrix:     true,
	})
	for _, test := range tests {
		a = []byte(test[0])
		b = []byte(test[1])

		r := alg.Global(a, b)

		fmt.Printf("%s", r.Matrix)
		fmt.Printf("matches: %d, gaps: %d, len: %d, identity: %.2f%%\n",
			r.Matches, r.Gaps, r.Len, float64(r.Matches)/float64(r.Len)*100)
		fmt.Printf("%s\n", r.AlignA)
		fmt.Printf("%s\n", r.AlignM)
		fmt.Printf("%s\n", r.AlignB)

		RecycleAlignResult(r)
	}
}
