package cmd

import (
	"encoding/json"
	"math"
	"os"
	"reflect"
	"slices"
	"testing"
)

func TestSeedChainBoundsMatchesPathBasedChainer(t *testing.T) {
	// Scores and bounds were generated by the path-based implementation at
	// 8efb43a, including its alignment-region sorting and reverse endpoints.
	data, err := os.ReadFile("testdata/seed-chain-bounds.json")
	if err != nil {
		t.Fatal(err)
	}
	type region struct {
		QBegin, QEnd, TBegin, TEnd, FirstTBegin int32
		RC                                      bool
	}
	var cases []struct {
		Name      string
		Subs      []SubstrPair
		Options   ChainingOptions
		Regions   []region
		ScoreBits uint32
	}
	if err := json.Unmarshal(data, &cases); err != nil {
		t.Fatal(err)
	}
	for _, tt := range cases {
		t.Run(tt.Name, func(t *testing.T) {
			chainer := NewChainer(&tt.Options)
			regions, score := chainer.Chain(&tt.Subs, nil)
			got := make([]region, 0, len(regions))
			for _, r := range regions {
				got = append(got, region{r.qBegin, r.qEnd, r.tBegin, r.tEnd, r.firstTBegin, r.rc})
			}
			if math.Float32bits(score) != tt.ScoreBits || !reflect.DeepEqual(got, tt.Regions) {
				t.Fatalf("score bits = %x, want %x; regions = %+v, want %+v", math.Float32bits(score), tt.ScoreBits, got, tt.Regions)
			}
		})
	}
}

func TestSeedChainRegionStorageReuseAndOwnership(t *testing.T) {
	chainer := NewChainer(&ChainingOptions{MinScore: 1, MaxDistance: 1, MaxGap: 1, TopChains: -1})
	subs := []SubstrPair{
		{QBegin: 0, TBegin: 200, Len: 31},
		{QBegin: 100, TBegin: 100, Len: 31},
		{QBegin: 200, TBegin: 0, Len: 31},
	}
	r := &SearchResult{}
	r.resetChainRegions()
	r.chainRegions, r.Score = chainer.Chain(&subs, r.chainRegions)
	if len(r.chainRegions) != 3 {
		t.Fatalf("got %d independent chains, want 3", len(r.chainRegions))
	}
	backing := &r.chainRegions[0]
	want := slices.Clone(r.chainRegions)
	r.Reset()
	r.chainRegions, r.Score = chainer.Chain(&subs, r.chainRegions)
	if &r.chainRegions[0] != backing || !slices.Equal(r.chainRegions, want) {
		t.Fatal("recycled candidate did not reuse its multi-chain buffer")
	}
	// Reusing the chainer and changing anchor coordinates must not change
	// regions already returned to a different candidate.
	for i := range subs {
		subs[i].TBegin += 1000
	}
	other, _ := chainer.Chain(&subs, nil)
	if !slices.Equal(r.chainRegions, want) || slices.Equal(other, want) {
		t.Fatal("returned regions retain references to anchors or chainer scratch")
	}
}
